language: node_js
node_js:
  - "6"
services: 
  - mongodb
install:
  - npm install
script:
  - npm run test
env:
  - NODE_ENV=development
deploy:
  provider:
    heroku
  api_key:
    secure: nrUXDEC/0DWJQdSmceeTSPRPcySbsY3Ezst2CBi899oNTFpZJw8RggN8mj6AVCaETZIEfy5qzwUyUrjYBALLVCCt+VqV3zV0iCG5vbtR5xFt7IKagsv6Jm2Kw2Q3M6DBg4Lr+Nuk2BzN8H4Kp8PmRjMl4Z+s3wNUiMtxiLsOQRqTgbuqTFeoD/jjv6xeW7VWPsgx1jcgUI54XdIzl1GhRZoL33S9FQ7zrBDQJZR3kveqoklgJcVgpwqb5wtgmiuciAISMUEKRzcr4zozmmm2+DtPO6uz/NTXyGRiychZcgHcn9PyIrib7mcc8NfDErMhlPcTtFLoB+kWrmbKK3IKt65gGGu3r4PGaxJen5Y70tL4RrCbGpeTHzcTp5wLyelQMhDycNls/j+5iYLI5NgoV9I/yH2e/QeXbpVtbeBjTMa5gjqUg+1ZaMX3nL22M4rH8MbIgVI9L1f9FgYqNtr0/nYN8OmL2B+iIqXHt3yMDqur59zK5YzYDuKmPiQJ+6aGZYP6gNYO4CUG0xinoOf5R9VTF9AWM4ZKXaKj1reIAwv3aG5K+4eEFeOJZGTSzo4UMFQDXIZ1K8K7Cp21NVWK/0RDpTTgYivp8vquyvJL1KYRioqTp6tZXlPrMTqFfidlq3ErtAfSCMe75HTFg4HaKTO58NqjmN5Y9ktSIOYTbAs=
